### ISSUE TITLE
Describe branching and merging process in documentation

### ISSUE THREAD

**Issue by adrianbrink** [tendermint/coding#26] opened 2017-08-31 06:55 UTC
- create branches on the repo itself not on a fork to allow other maintainers to rebase your code
- always squash merge into develop from a feature branch
- only use unstable if you need to integrate multiple feature branches before merging into develop
  - unstable should only live for the duration of the merge
- a merge into develop should comprise 1 commit with a properly formatted git title and message

**Comment by zramsay** [comment] 2017-10-09 19:37
a lot of this sort of depends on the repo and/or the fix/feature itself. Duplicate of #17

**Closed as completed by zramsay** 2017-10-09 19:37 UTC
